### ISSUE TITLE
release checklist

### ISSUE THREAD

**Issue by knaaptime** [pysal/segregation#72]
# TODO Prior to next release:

## Critical

- [x] RX: rename `profile` to `compute_all()`
- [x] RX: `compute_all` should return a pandas.DataFrame instead of a dict
- [x] RX: smart counterfactual approach
- [x] RX: decide on distance decay isolation name
- [x] EK: docstrings for network funcs
- [x] EK: dosctrings for util plots
- [x] EK: add tests for network measures
- [x] EK: move `udst` dependencies into `extra_requirements.txt` and add warning to network functions
- [ ] EK: update readme
	- [ ] add DOI badge to readme
	- [x] add network example

## Minor:
- decide on signature for spatial indices  as discussed [here](https://github.com/pysal/segregation/issues/2#issuecomment-502830523)
e.g.:
```
def localize(data, w):
	new_data = []
	w = pysal.weights.insert_diagonal(w) # attach focal unit to environment
	for y in data:
		new_data.append(lag_spatial(w,y)
	return new_data
```

**Comment by renanxcortes** [comment]
@knaaptime , please let me know if you'd like some help with the network points.

**Comment by renanxcortes** [comment]
Closing since this is checklist for the 1.1.0 release which is already out.
